### PR TITLE
Add rst simple table support

### PR DESCRIPTION
**Pull request by wandns**

### CODE REVIEW

**Comment by vovkos** [comment]
This commit seems to be in conflict with your previous one (regarding ulink support).

Also, please declare Lua local variables (such as tbl, maxwidth, etc) as 'local' so that these names don't (unintentionally) pollute the global namespace.

**Comment by vovkos** [comment]
Also, there's a *major* update/redesign coming. A lot has been changed and moved around. So after fixing this pull request, please don't submit more -- wait until I carefully merge branches (later this week). Thanks!

**Comment by wandns** [comment]
Ok, I've rebased and added local scope specifier.

Thanks for the nice tool, and pardon my Lua...I'm a complete noob when it comes to that language :).

**Comment by vovkos** [comment]
Thanks! And no worries about your Lua, that was just a small thing.

**Pull request merged**
